{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"snowball_output\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "3ad81894-a62f-4452-8543-a52803963cf9",
        "fromColumn": "Date",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bdc433b9-e9f2-4e04-b882-5301a68b752d"
      },
      {
        "name": "00ad198e-8996-4856-b4f4-ed083f8c2512",
        "fromColumn": "EOW - Saturday",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_df63856f-dfce-4f6d-b7cf-3663b3bc1cbb"
      },
      {
        "name": "a2ff202d-6a8c-5e66-a3c1-a9b0e21a3a2f",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "month_roll",
        "fromTable": "snowball_output",
        "toColumn": "Date",
        "toTable": "Calendar"
      }
    ],
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "snowball_output",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "snowball_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d781d72-2a6b-40ab-bd87-d3df881b4617",
            "sourceColumn": "snowball_key",
            "summarizeBy": "none"
          },
          {
            "name": "customer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e22cfe49-7854-4fd2-a791-80e1dbfc4e6d",
            "sourceColumn": "customer_key",
            "summarizeBy": "none"
          },
          {
            "name": "product_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91621235-74b5-4773-9696-69bf98535c18",
            "sourceColumn": "product_key",
            "summarizeBy": "none"
          },
          {
            "name": "month_roll",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c363dc20-d86f-4ca1-8c2a-b390e4f81657",
            "sourceColumn": "month_roll",
            "summarizeBy": "none"
          },
          {
            "name": "period_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dafe9081-f213-44fd-af83-32d45204a3d7",
            "sourceColumn": "period_type",
            "summarizeBy": "none"
          },
          {
            "name": "bop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "152a6670-ba97-4d5c-a6fd-a019b1c6e04d",
            "sourceColumn": "bop_arr",
            "summarizeBy": "sum"
          },
          {
            "name": "customer_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d253ddec-e00d-43a8-a0b7-fd115750fb19",
            "sourceColumn": "customer_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "product_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ad2f3e02-7cc3-4079-8d5c-a63bd09e1507",
            "sourceColumn": "product_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "downsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "27e67f4c-6047-4519-83ae-4af539d64e17",
            "sourceColumn": "downsell",
            "summarizeBy": "sum"
          },
          {
            "name": "grr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7e511c74-2736-47d0-ba4f-b2f083332060",
            "sourceColumn": "grr",
            "summarizeBy": "sum"
          },
          {
            "name": "upsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0579f9a0-9cd2-4a6e-849f-b688cc8bf559",
            "sourceColumn": "upsell",
            "summarizeBy": "sum"
          },
          {
            "name": "cross_sell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "34e1b6a7-54e1-4989-8608-c8bf0f92df10",
            "sourceColumn": "cross_sell",
            "summarizeBy": "sum"
          },
          {
            "name": "nrr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d2fdd3d2-cf88-4bad-a49e-9e9f688108b2",
            "sourceColumn": "nrr",
            "summarizeBy": "sum"
          },
          {
            "name": "new_customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67551dd0-2533-407c-a78a-04e8b812f7f1",
            "sourceColumn": "new_customer",
            "summarizeBy": "sum"
          },
          {
            "name": "eop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8117fcf4-a542-490f-a96d-63c71ca5fd76",
            "sourceColumn": "eop_arr",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "3716bee0-578b-4896-932f-a7947f7faed6",
        "partitions": [
          {
            "name": "snowball_output",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\VijayR\\Downloads\\snowball_output.csv\"),[Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"snowball_key\", type text}, {\"customer_key\", type text}, {\"product_key\", type text}, {\"month_roll\", type date}, {\"period_type\", type text}, {\"bop_arr\", type number}, {\"customer_churn\", type number}, {\"product_churn\", type number}, {\"downsell\", type number}, {\"grr\", type number}, {\"upsell\", type number}, {\"cross_sell\", Int64.Type}, {\"nrr\", type number}, {\"new_customer\", type number}, {\"eop_arr\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_ee63f18d-cacb-49c3-8063-5dc0ab4470d8",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4299a205-f2fd-432d-8ba4-430a4a510794",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "73a26303-66c9-47be-a597-9b2927c6f033",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "99d712e7-47a3-4b56-95cb-125c58daee76",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a3200190-77da-4a1d-b925-6dd374842e63",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "07c148ce-bddc-4b91-8456-49b056637c2d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "85a754be-61c2-454c-b5dd-09010dbda942",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2bdfe303-5b18-4e71-a015-0b78368a2c2a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2512033e-b69e-4cb0-a0e6-7ea4662952f9",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "08204071-b460-4b35-b152-03c5fad2f403",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b78b4ee1-6873-4eb3-a2df-99e7a38be90f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "49507fba-f1a5-4da9-92d2-11c1bb92bea7",
                "ordinal": 3
              }
            ],
            "lineageTag": "eaac4b48-ce78-4618-8d54-e3f527db3975"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "baafffdc-2398-4e91-a531-cf3bba9f8074",
        "partitions": [
          {
            "name": "DateTableTemplate_ee63f18d-cacb-49c3-8063-5dc0ab4470d8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9e4a1273d6ca4d0a8d3d51619cd80ffa"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9c9d2032-fb33-4269-b72b-84fa5ced27ea",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bdc433b9-e9f2-4e04-b882-5301a68b752d"
                },
                "isDefault": true,
                "relationship": "3ad81894-a62f-4452-8543-a52803963cf9"
              }
            ]
          },
          {
            "name": "DateAsInteger",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "430616fd-d15b-4d82-b9bb-a914d0d5975a",
            "sourceColumn": "[DateAsInteger]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6ce974ec-dcaa-47b5-9146-560749266c87",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year less 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1f74ac20-628f-4947-a2bf-7bc63c9a0c60",
            "sourceColumn": "[Year less 1]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2ef94241-70a7-4051-8613-e17c16a6bb0f",
            "sourceColumn": "[MonthYear]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "QuarterYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4522300e-ddbc-4640-86eb-2c6446589392",
            "sourceColumn": "[QuarterYear]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "868583f2-93f2-4017-b91a-d1768b0ffed8",
            "sourceColumn": "[MonthNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5d9112a6-808a-44dc-9041-4ece8a1f3bc0",
            "sourceColumn": "[MonthText]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "17faa874-ca6a-426e-a778-de3b0cdece4d",
            "sourceColumn": "[YearMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YMInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bf8494fd-aa90-432e-baa1-6d6531efcc0d",
            "sourceColumn": "[YMInt]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WeekdayNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "993c687e-fc1b-42aa-9ed1-ffbf4347ce9b",
            "sourceColumn": "[WeekdayNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year & Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ba344dde-68e9-4f82-ba79-d9f00cbb6fc6",
            "sourceColumn": "[Year & Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3a07aef7-e79a-4fc1-a49e-eed604139b33",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7e069168-8321-4aaf-b431-272a29ff98f5",
            "sourceColumn": "[WeekNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "EOW - Saturday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a6de4e3f-280f-4faa-bb96-238a66dd52eb",
            "sourceColumn": "[EOW - Saturday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_df63856f-dfce-4f6d-b7cf-3663b3bc1cbb"
                },
                "isDefault": true,
                "relationship": "00ad198e-8996-4856-b4f4-ed083f8c2512"
              }
            ]
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "af058b29-1462-48ee-b45a-34aaee240d62",
            "sourceColumn": "[Weekday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "09942f1c-163a-4deb-af26-3128cc2b161e",
            "sourceColumn": "[DayNo]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5b95fdc1-633d-4ea7-84e6-178e2cdff397",
            "sourceColumn": "[DayMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "a398cde0-f5f0-4890-af51-be25d0884f88",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "ADDCOLUMNS(CALENDAR(date(2017,01,01),date(2026,12,31)),",
                "\"DateAsInteger\", FORMAT ( [Date], \"YYYYMMDD\" ), ",
                "\"Year\", FORMAT([Date], \"yyyy\"), ",
                "\"Year less 1\", FORMAT([Date], \"yyyy\")-1,",
                "\"MonthYear\", FORMAT([Date],\"mmm yy\"),",
                "\"QuarterYear\", FORMAT([Date],\"yyyy \\QQ\"), ",
                "\"MonthNo\", MONTH([Date]),",
                "\"MonthText\", FORMAT([Date], \"mmm\"),",
                "\"YearMonth\", FORMAT([Date], \"MMMM-YYYY\"),",
                "\"YMInt\", 13 * YEAR([Date]) + MONTH([Date]),",
                "\"WeekdayNo\", WEEKDAY([Date],2),",
                "\"Year & Month\", FORMAT([Date],\"MMM-YY\"),",
                "\"Month\", FORMAT([Date], \"mmmm\"), ",
                "\"WeekNo\", WEEKNUM([Date]),",
                "\"EOW - Saturday\", [Date]+7-WEEKDAY([Date]-7),",
                "\"Weekday\", FORMAT([Date], \"dddd\"), ",
                "\"DayNo\", FORMAT([Date], \"d\"),",
                "\"DayMonth\", FORMAT([Date], \"dd mmm\")",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_bdc433b9-e9f2-4e04-b882-5301a68b752d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "87e1c9a5-426e-4b6d-9674-05c9156d280c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7667073c-6faa-4cfc-9386-dfad2cfa7d81",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5eaf9ebf-88e1-4fbf-8c30-b49e88b067f1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0641f292-98b0-45b5-83e3-86d147c8cb2c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "55f2940a-f9c5-46e1-955e-2458d377df3f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "33d58f70-2bb0-47f1-9f01-350c0e5465e8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "00d7403b-7347-4322-b08e-420e871653fc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "73e82609-1c68-4c5b-81e1-0b9d87d94927",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4075fa5f-d9c4-49d2-8dbc-2b2fbcf91294",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c88a8eb0-02a7-4e49-8084-e12b529c110e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7f46b82f-304a-4f85-8621-5cbe8eca8ab0",
                "ordinal": 3
              }
            ],
            "lineageTag": "17e0ded1-5f50-4ef7-803f-5dee6432aa78"
          }
        ],
        "isHidden": true,
        "lineageTag": "8a1939a1-ef32-46fe-9fe8-a91b2c751424",
        "partitions": [
          {
            "name": "LocalDateTable_bdc433b9-e9f2-4e04-b882-5301a68b752d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[Date])), 1, 1), Date(Year(MAX('Calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_df63856f-dfce-4f6d-b7cf-3663b3bc1cbb",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a1eab0c5-dccc-4c03-b936-f1ecc05b6868",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3d584347-9604-45cd-ba0e-7cec40c6e23e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e7eb9471-1101-422a-831a-5906e069dbe3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "15cac1c6-53bf-4a61-ab57-4a9413bffb40",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f7eb2f62-f951-4b05-8dd2-d0c1f620a734",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "19123cde-ab67-4c8a-be55-06dd614d7dd8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "40a5cf4a-aa05-4fdc-9f76-c2fdee7a27fe",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "177efc59-0835-4a6d-98ae-d0839455a8b6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6adbf5cb-a9d2-45b9-87aa-490aadf168f6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c1a29d13-e508-4871-b2ee-29a76f0b466f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b7a1e038-14d1-4796-ab2a-da2d0af3c98a",
                "ordinal": 3
              }
            ],
            "lineageTag": "97e3cd6c-501a-45d6-8182-d923f9a7dce7"
          }
        ],
        "isHidden": true,
        "lineageTag": "577ea80f-3fdc-4060-b401-ea8b6f0c0464",
        "partitions": [
          {
            "name": "LocalDateTable_df63856f-dfce-4f6d-b7cf-3663b3bc1cbb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[EOW - Saturday])), 1, 1), Date(Year(MAX('Calendar'[EOW - Saturday])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}